name: Test Impact

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**/*.py'
  workflow_dispatch:

jobs:
  analyze:
    uses: vindicta-platform/.github/.github/workflows/test-impact-template.yml@main
    permissions:
      contents: read
      pull-requests: write
